version: '3'
services:
  backend:
    build:
      context: backend 
    command: npm run start:dev
    ports:
     - "3000:3000"
    volumes:
     - "./backend:/usr/src/app"
     - node_modules:/app/node_modules
  mongo:
    ports:
     - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: jobs
volumes:
  node_modules: